<?php
require_once __DIR__ . '/libs/TCPDF-main/tcpdf.php';

// Kapcsolódás az adatbázishoz
$con = new mysqli('localhost', 'root', '', 'nb1');
if ($con->connect_error) {
    die('Connection failed: ' . $con->connect_error);
}

// Felhasználói bemenetek
$username = $_POST['username'];
$club = $_POST['club'];
$position = $_POST['position'];

// Adatok lekérdezése az adatbázisból
$query = $con->prepare("
    SELECT a.username, k.csapatnev, l.utonev, l.vezeteknev, l.mezszam, l.ertek, p.nev AS poszt
    FROM accounts a
    JOIN labdarugo l ON a.id = l.felhasznalo_id
    JOIN klub k ON l.klubid = k.id
    JOIN poszt p ON l.posztid = p.id
    WHERE a.username = ? AND k.csapatnev = ? AND p.nev = ?
");
$query->bind_param('sss', $username, $club, $position);
$query->execute();
$result = $query->get_result();
$data = $result->fetch_all(MYSQLI_ASSOC);

// Ha nincs találat
if (empty($data)) {
    die('No data found for the given criteria.');
}

// PDF generálása
$pdf = new TCPDF();
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Website');
$pdf->SetTitle('User Data PDF');
$pdf->SetHeaderData('', '', 'PDF Generator', 'Generated by TCPDF');
$pdf->setHeaderFont(['helvetica', '', 12]);
$pdf->setFooterFont(['helvetica', '', 10]);
$pdf->SetMargins(15, 27, 15);
$pdf->SetAutoPageBreak(TRUE, 25);
$pdf->AddPage();

// HTML tartalom létrehozása
$html = "<h1>Selected Data</h1>";
foreach ($data as $row) {
    $html .= "<p><strong>Username:</strong> " . htmlspecialchars($row['username']) . "</p>";
    $html .= "<p><strong>Club:</strong> " . htmlspecialchars($row['csapatnev']) . "</p>";
    $html .= "<p><strong>Player Name:</strong> " . htmlspecialchars($row['vezeteknev'] . ' ' . $row['utonev']) . "</p>";
    $html .= "<p><strong>Jersey Number:</strong> " . htmlspecialchars($row['mezszam']) . "</p>";
    $html .= "<p><strong>Position:</strong> " . htmlspecialchars($row['poszt']) . "</p>";
    $html .= "<p><strong>Value:</strong> " . htmlspecialchars($row['ertek']) . "M</p><hr>";
}

// PDF-be írás
$pdf->writeHTML($html, true, false, true, false, '');

// PDF letöltése
$pdf->Output('generated_report.pdf', 'D');

// Kapcsolat bezárása
$con->close();
?>
